# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pa <- function(p, MOI, min_time, max_time, rep, write) {
    .Call('_spide_pa', PACKAGE = 'spide', p, MOI, min_time, max_time, rep, write)
}

avepa <- function(p, MOI, min_time, max_time, write) {
    .Call('_spide_avepa', PACKAGE = 'spide', p, MOI, min_time, max_time, write)
}

sig <- function(p0) {
    .Call('_spide_sig', PACKAGE = 'spide', p0)
}

track_mutants <- function(p, MOI, min_time, max_time) {
    .Call('_spide_track_mutants', PACKAGE = 'spide', p, MOI, min_time, max_time)
}

avetrack <- function(p, MOI, min_time, max_time) {
    .Call('_spide_avetrack', PACKAGE = 'spide', p, MOI, min_time, max_time)
}

